replicaCount: 1
deployment:
  name: udb2-api
db: 
  url: jdbc:postgresql://udb2-db-service:5432/udb
  configMap: udb2-db-configmap
buildConfig:
  uri: https://github.com/qiao2/udb.git
  contextDir: /api
imageStream:
  namespace: udb
  name: udb-api
  tag: latest
service:
  port: 8080