apiVersion: v1
kind: Service
metadata:
  name: udb-api-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
  selector:
    app: udb-api
    deploymentconfig: udb-api
