replicaCount: 1
deployment:
  name: udb2-ui
udbServiceHost: udb2-api-route-udb.apps-crc.testing
buildConfig:
  uri: https://github.com/qiao2/udb.git
  contextDir: /ui
imageStream:
  namespace: udb
  name: udb-ui
  tag: latest
service:
  port: 8080