apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: 8080-tcp
  selector:
    app: {{ .Values.deployment.name }}
    deploymentconfig: {{ .Values.deployment.name }}
