db:
  replicaCount: 1
  deployment:
    name: udb-db
  imageStream:
    namespace: openshift
    name: postgresql
    tag: 12-el8
  configMap:
    db: udb
    username: jtims
    password: password
  service:
    port: 5432
  
api:
  replicaCount: 1
  deployment:
    name: udb-api
  db: 
    url: jdbc:postgresql://udb-db-service.pipeline.svc.cluster.local:5432/udb
    configMap: udb-db-configmap
  buildConfig:
    uri: https://github.com/qiao2/udb.git
    contextDir: /api
  imageStream:
    namespace: pipeline
    name: udb-helm
    tag: latest
  service:
    port: 8080
  
ui:
  replicaCount: 1
  deployment:
    name: udb-ui
  udbServiceHost: udb-api-service.pipeline.svc.cluster.local
  buildConfig:
    uri: https://github.com/qiao2/udb.git
    contextDir: /ui
  imageStream:
    namespace: pipeline
    name: swagger-ui-helm
    tag: latest
  service:
    port: 8080