kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app.openshift.io/runtime: spring-boot
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - {{ .Values.deployment.name }}
        from:
          kind: ImageStreamTag
          namespace: {{ .Values.imageStream.namespace }}
          name: {{ .Values.imageStream.name }}:{{ .Values.imageStream.tag }}
    - type: ConfigChange
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  test: false
  selector:
    app: {{ .Values.deployment.name }}
    deploymentconfig: {{ .Values.deployment.name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.deployment.name }}
        deploymentconfig: {{ .Values.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: " "
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db.configMap }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.db.configMap }}
                  key: password
            - name: DB_URL
              value: {{ .Values.db.url }}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
