kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.deployment.name }}-route
spec:
  to:
    kind: Service
    name: {{ .Values.deployment.name }}-service
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None
